export const odsList = {
	1: 'Erradicação da pobreza',
	2: 'Fome zero e agricultura sustentável',
	3: 'Saúde e bem-estar',
	4: 'Educação de qualidade',
	5: 'Igualdade de gênero',
	6: 'Água potável e saneamento',
	7: 'Energia acessível e limpa',
	8: 'Trabalho decente e crescimento econômico',
	9: 'Indústria, inovação e infraestrutura',
	10: 'Redução das desigualdades',
	11: 'Cidades e comunidades sustentáveis',
	12: 'Consumo e produção responsáveis',
	13: 'Ação contra a mudança global do clima',
	14: 'Vida na água',
	15: 'Vida terrestre',
	16: 'Paz, justiça e instituições eficazes',
	17: 'Parcerias e meios de implementação',
}
